export type UserRole = "client" | "admin" | "receptionist"
export type OrderStatus =
  | "pending"
  | "paid"
  | "awaiting_shipping_payment"
  | "shipping_paid"
  | "shipped"
  | "delivered"
  | "cancelled"

export type ShippingPaymentStatus = "not_required" | "pending" | "paid" | "waived"
export type AppointmentStatus = "pending" | "paid" | "completed" | "cancelled"
export type CourseLevel =
  | "beginner"
  | "intermediate"
  | "advanced"
  | "open"
export type RegistrationStatus = "pending" | "paid" | "cancelled"
export type PaymentStatus = "pending" | "approved" | "rejected" | "refunded"
export type PaymentProvider = "mercadopago" | "stripe"
export type EntityType = "order" | "appointment" | "course"
export type DeliveryType = "shipping" | "pickup" | "local_delivery"
export type AppointmentType = "individual" | "group"
