export type UserRole = "client" | "admin"
export type OrderStatus =
  | "pending"
  | "paid"
  | "shipped"
  | "delivered"
  | "cancelled"
export type AppointmentStatus = "pending" | "paid" | "completed" | "cancelled"
export type CourseLevel =
  | "beginner"
  | "intermediate"
  | "advanced"
  | "open"
export type RegistrationStatus = "pending" | "paid" | "cancelled"
export type PaymentStatus = "pending" | "approved" | "rejected" | "refunded"
export type PaymentProvider = "mercadopago" | "stripe"
export type EntityType = "order" | "appointment" | "course"
export type DeliveryType = "shipping" | "pickup"
export type AppointmentType = "individual" | "group"
